// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQh2capOto3YyXuitp9K2t6yivcryepmY',
    appId: '1:1014643017418:web:0a7c6df545b4225fb31633',
    messagingSenderId: '1014643017418',
    projectId: 'snake-classic-8f50a',
    authDomain: 'snake-classic-8f50a.firebaseapp.com',
    storageBucket: 'snake-classic-8f50a.firebasestorage.app',
    measurementId: 'G-3ESFWRP852',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8ZtB6dVfNjdllhjVpFMX7OFto0rIF2bQ',
    appId: '1:1014643017418:android:21495ae5b49720ebb31633',
    messagingSenderId: '1014643017418',
    projectId: 'snake-classic-8f50a',
    storageBucket: 'snake-classic-8f50a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnyQRTI_lhdKDnCX-2JLChnG7xMG__Mh0',
    appId: '1:1014643017418:ios:840c8d89f551b02fb31633',
    messagingSenderId: '1014643017418',
    projectId: 'snake-classic-8f50a',
    storageBucket: 'snake-classic-8f50a.firebasestorage.app',
    iosBundleId: 'com.pranta.snakeclassic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnyQRTI_lhdKDnCX-2JLChnG7xMG__Mh0',
    appId: '1:1014643017418:ios:840c8d89f551b02fb31633',
    messagingSenderId: '1014643017418',
    projectId: 'snake-classic-8f50a',
    storageBucket: 'snake-classic-8f50a.firebasestorage.app',
    iosBundleId: 'com.pranta.snakeclassic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQh2capOto3YyXuitp9K2t6yivcryepmY',
    appId: '1:1014643017418:web:524c55395a7c9771b31633',
    messagingSenderId: '1014643017418',
    projectId: 'snake-classic-8f50a',
    authDomain: 'snake-classic-8f50a.firebaseapp.com',
    storageBucket: 'snake-classic-8f50a.firebasestorage.app',
    measurementId: 'G-LKDC5EP7XZ',
  );
}
