"""Generates lib/design/lb_glyphs.dart from the Living Board design JSON.

    python tools/gen_lb_glyphs.py

Sources: docs/living-board/design/cell_font_3x5.json and pixel_icons_5x5.json.
The kit font has no J or Q and only a few symbols, so EXTRA_GLYPHS fills the
gaps the copy deck needs. Edit the JSON (or EXTRA_GLYPHS) and re-run; never
hand-edit the generated file.
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
DESIGN = ROOT / "docs" / "living-board" / "design"
OUT = ROOT / "lib" / "design" / "lb_glyphs.dart"

EXTRA_GLYPHS = {
    "J": ["001", "001", "001", "101", "111"],
    "Q": ["111", "101", "101", "111", "011"],
    ":": ["0", "1", "0", "1", "0"],
    "+": ["000", "010", "111", "010", "000"],
    "%": ["101", "001", "010", "100", "101"],
    ",": ["00", "00", "00", "01", "10"],
    "'": ["1", "1", "0", "0", "0"],
    "#": ["01010", "11111", "01010", "11111", "01010"],
    "×": ["000", "101", "010", "101", "000"],  # ×
    "<": ["001", "010", "100", "010", "001"],
    ">": ["100", "010", "001", "010", "100"],
    "¢": ["010", "111", "100", "111", "010"],  # ¢
}


def dart_str(s: str) -> str:
    return "'" + s.replace("\\", "\\\\").replace("'", "\\'").replace("$", "\\$") + "'"


def main() -> None:
    font = json.loads((DESIGN / "cell_font_3x5.json").read_text(encoding="utf-8"))
    icons = json.loads((DESIGN / "pixel_icons_5x5.json").read_text(encoding="utf-8"))
    glyphs = dict(font["glyphs"])
    for k, v in EXTRA_GLYPHS.items():
        glyphs.setdefault(k, v)

    lines = [
        "// GENERATED by tools/gen_lb_glyphs.py from docs/living-board/design/.",
        "// Do not edit by hand.",
        "",
        "/// 3x5 cell font. Each glyph is 5 rows; '1' is a lit cell. Glyphs are",
        "/// separated by one empty column when drawn.",
        "const Map<String, List<String>> lbCellGlyphs = {",
    ]
    for k in sorted(glyphs):
        rows = ", ".join(dart_str(r) for r in glyphs[k])
        lines.append(f"  {dart_str(k)}: [{rows}],")
    lines += [
        "};",
        "",
        "/// 5x5 pixel icons. 'x' = primary colour, 'o' = accent, '.' = empty.",
        "const Map<String, List<String>> lbPixelIconData = {",
    ]
    for k in sorted(icons["icons"]):
        rows = ", ".join(dart_str(r) for r in icons["icons"][k])
        lines.append(f"  {dart_str(k)}: [{rows}],")
    lines += ["};", ""]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(glyphs)} glyphs, {len(icons['icons'])} icons")


if __name__ == "__main__":
    main()
